kind: DeploymentConfig
apiVersion: v1
metadata:
  name: testopenshift
  labels:
    app: testopenshift
spec:
  template:
    metadata:
      name: testopenshift
      labels:
        app: testopenshift
    spec:
      containers:
        - name: testopenshift-container
          image: 172.30.1.1:5000/myproject/testopenshift:1
          ports:
            - containerPort: 8080
              protocol: TCP
          command:
            - uwsgi uwsgi.ini
  replicas: 1
  strategy:
    type: Rolling
  paused: false