apiVersion: v1
kind: Template
metadata:
  name: mongodb-template
  labels:
    app: testopenshift
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongodb-claim
      labels:
        app: testopenshift
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes:
        - ReadWriteOnce

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: mongodb-deployment
      labels:
        role: database
    spec:
      template:
        metadata:
          name: mongodb
          labels:
            role: database
            app: testopenshift
        spec:
          containers:
            - name: mongodb
              image: mongo:latest
              ports:
                - containerPort: 27017
                  protocol: TCP

              volumeMounts:
                - name: data
                  mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin

          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: mongodb-claim

          replicas: 1
          paused: false
          strategy:
            type: Rolling


  - apiVersion: v1
    kind: Service
    metadata:
      name: mongodb-service
      labels:
        app: testopenshift
    spec:
      ports:
        - name: mongodb-port
          NodePort: 0
          targetPort: 27017
          port: 27017
          protocol: TCP
      selector:
        role: database